export const FEED = {
  LOAD_GIFS_REQUEST: "FEED/LOAD_GIFS_REQUEST",
  LOAD_GIFS_SUCCESS: "FEED/LOAD_GIFS_SUCCESS",
  UPDATE_GIFS_SUCCESS: "FEED/UPDATE_GIFS_SUCCESS",
  LOAD_GIFS_ERROR: "FEED/LOAD_GIFS_ERROR"
};
